version: '3'

services:

  api:
    container_name: flask
    build: .
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redis:
    container_name: redis_auth
    image: redis:7.0.5
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  elasticsearch:
    container_name: elasticsearch_auth
    image: elasticsearch:8.4.1 #docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "localhost:9200/_cat/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - elasticsearch_data:/elasticsearch/data

  nginx:
    image: nginx:1.23.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  elasticsearch_data:
    external:
      name: elasticsearch_data
  redis_data: